In [1]:
import numpy as np

In [2]:
I = np.array([1,5,7,21,9,14,25,40,3,15,40,26,9,20,42,29,29,2,31,13,22,4,47,4,29]).reshape((5,-1))
I

array([[ 1,  5,  7, 21,  9],
       [14, 25, 40,  3, 15],
       [40, 26,  9, 20, 42],
       [29, 29,  2, 31, 13],
       [22,  4, 47,  4, 29]])

In [24]:
def integral_image_brute_force(I):
    J = np.zeros(I.shape)
    for i in range(J.shape[0]):
        for j in range(J.shape[1]):
            J[i,j] = np.sum(I[0:i+1, 0:j+1])
    return J

In [25]:
integral_image_brute_force(I)

array([[  1.,   6.,  13.,  34.,  43.],
       [ 15.,  45.,  92., 116., 140.],
       [ 55., 111., 167., 211., 277.],
       [ 84., 169., 227., 302., 381.],
       [106., 195., 300., 379., 487.]])

In [26]:
def integral_image_smart(I):
    J = np.zeros(I.shape)
    
    J[0, 0] = I[0, 0]
    
    for i in range(1, J.shape[0]):
        J[i, 0] = J[i-1, 0] + I[i, 0]
        
    for j in range(1, J.shape[1]):
        J[0, j] = J[0, j-1] + I[0, j]
    
    for i in range(1, J.shape[0]):
        for j in range(1, J.shape[1]):
            J[i,j] = I[i, j] + J[i-1,j] + J[i, j-1] - J[i-1, j-1]
    return J

In [27]:
integral_image_smart(I)

array([[  1.,   6.,  13.,  34.,  43.],
       [ 15.,  45.,  92., 116., 140.],
       [ 55., 111., 167., 211., 277.],
       [ 84., 169., 227., 302., 381.],
       [106., 195., 300., 379., 487.]])